### ISSUE TITLE
Add solpolpy "shortcut" test

### ISSUE THREAD

**Issue by jmbhughes** [punch-mission/solpolpy#68]
We can convert MZP -> BpB -> Stokes or just go straight MZP -> Stokes without doing the intermediate conversion. It would be good to add tests to make sure the former scenario's output is close to the latter scenario's output. 

* work log*:
- @s0larish : ? hours

**Comment by s0larish** [comment]
I just rechecked, the conversions having alternate paths are not these, but BtBr->BpB->MZP and BtBr->MZP. Working on it. Just for a note here.

**Comment by s0larish** [comment]
Closed #68 in 1 hr
